---
- hosts: localhost
  gather_facts: no
  tasks:
    - setup:
        gather_subset: '!all'
      async: 60
      poll: 5
    - shell: echo Hello `hostname`
      register: result
  tasks:
    - name: vm delete
      include_role:
        name: vmdelete 
