---
- name: vm delete
  hosts: 192.168.29.237
  gather_facts: False

  tasks:
  - name: Delete Vms
    vmware_guest:
      hostname: "{{ list_host }}"
      user: "{{ vcenter_user }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: "{{ item }}"
      state: absent
    delegate_to: localhost
    with_lines: cat vmname.txt
